from __future__ import annotations

# Evaluate YOLO OBB on randomized Isaac evidence generated by
# isaac_yolo_confusion_matrix.py.
#
# Run with normal Python, not Isaac Python:
# python3 tools/training/yolo_confusion_from_samples.py \
#   --samples-csv work/confusion_matrix_hard_v2/samples.csv

import argparse
import csv
import math
import os
from pathlib import Path
import sys

import cv2
import numpy as np
import torch
from ultralytics import YOLO
from ultralytics.utils.metrics import ConfusionMatrix

sys.path.append(str(Path(__file__).resolve().parents[2]))
from vision.vision_contracts import ObbDetection, empty_obb  # noqa: E402


CLASS_NAMES = {0: "steel_plate", 1: "steel_cube"}
TRUE_LABELS = ["steel_plate", "steel_cube"]
MATRIX_LABELS = ["steel_plate", "steel_cube", "background"]
BACKGROUND_LABEL = "background"


def parse_args():
    root = Path(__file__).resolve().parents[2]
    default_samples = root / "work" / "confusion_matrix_hard_v2" / "samples.csv"
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples-csv", default=str(default_samples))
    parser.add_argument("--model", default=str(root / "vision" / "models" / "yolo11s_obb_metal_hard-v2_refinetune_best.pt"))
    parser.add_argument("--device", default="auto", help="Use auto, cpu, or a CUDA device such as 0.")
    parser.add_argument("--imgsz", type=int, default=960)
    parser.add_argument("--conf", type=float, default=0.25)
    parser.add_argument("--iou-thres", type=float, default=0.45)
    parser.add_argument("--save-images", choices=("none", "failures", "all"), default="failures")
    parser.add_argument("--out-dir", default="", help="Default: parent directory of --samples-csv")
    return parser.parse_args()


def to_numpy(value):
    if hasattr(value, "detach"):
        value = value.detach()
    if hasattr(value, "cpu"):
        value = value.cpu()
    return np.asarray(value)


def corners_from_xywhr(cx, cy, width, height, angle):
    c = math.cos(angle)
    s = math.sin(angle)
    local = np.array(
        [
            [-width / 2.0, -height / 2.0],
            [width / 2.0, -height / 2.0],
            [width / 2.0, height / 2.0],
            [-width / 2.0, height / 2.0],
        ],
        dtype=np.float64,
    )
    rot = np.array([[c, -s], [s, c]], dtype=np.float64)
    pts = local @ rot.T + np.array([cx, cy], dtype=np.float64)
    return tuple((float(x), float(y)) for x, y in pts)


def best_obb_detection(result):
    obb = getattr(result, "obb", None)
    if obb is None or getattr(obb, "xywhr", None) is None:
        return empty_obb()

    xywhr = to_numpy(obb.xywhr)
    if xywhr.size == 0:
        return empty_obb()

    conf = to_numpy(obb.conf) if getattr(obb, "conf", None) is not None else np.ones(len(xywhr))
    cls = to_numpy(obb.cls) if getattr(obb, "cls", None) is not None else np.zeros(len(xywhr))
    best = int(np.argmax(conf))
    cx, cy, width, height, angle = xywhr[best].astype(float)

    if getattr(obb, "xyxyxyxy", None) is not None:
        corners_arr = to_numpy(obb.xyxyxyxy[best]).reshape(4, 2)
        corners = tuple((float(x), float(y)) for x, y in corners_arr)
    else:
        corners = corners_from_xywhr(cx, cy, width, height, angle)

    return ObbDetection(
        valid=True,
        class_id=int(cls[best]),
        confidence=float(conf[best]),
        center_px=(float(cx), float(cy)),
        corners_px=corners,
        width_px=float(width),
        height_px=float(height),
        angle_rad=float(angle),
    )


def infer(model, bgr, args):
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    device = None if args.device == "auto" else args.device
    results = model.predict(source=rgb, imgsz=args.imgsz, conf=args.conf, device=device, verbose=False)
    return best_obb_detection(results[0]) if results else empty_obb()


def predict_result(model, bgr, args):
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    device = None if args.device == "auto" else args.device
    results = model.predict(source=rgb, imgsz=args.imgsz, conf=args.conf, device=device, verbose=False)
    return results[0] if results else None


def detections_from_result(result):
    empty = {
        "cls": torch.zeros((0,), dtype=torch.float32),
        "conf": torch.zeros((0,), dtype=torch.float32),
        "bboxes": torch.zeros((0, 5), dtype=torch.float32),
    }
    if result is None:
        return empty
    obb = getattr(result, "obb", None)
    if obb is None or getattr(obb, "xywhr", None) is None:
        return empty

    xywhr = to_numpy(obb.xywhr)
    if xywhr.size == 0:
        return empty

    conf = to_numpy(obb.conf) if getattr(obb, "conf", None) is not None else np.ones(len(xywhr))
    cls = to_numpy(obb.cls) if getattr(obb, "cls", None) is not None else np.zeros(len(xywhr))
    return {
        "cls": torch.as_tensor(cls, dtype=torch.float32),
        "conf": torch.as_tensor(conf, dtype=torch.float32),
        "bboxes": torch.as_tensor(xywhr, dtype=torch.float32),
    }


def pred_name_from_det(det: ObbDetection):
    if not det.valid:
        return "no_detection"
    return CLASS_NAMES.get(det.class_id, "unknown")


def gt_polygon_from_row(row):
    if row["true_class"] == BACKGROUND_LABEL:
        return np.zeros((0, 2), dtype=np.float64)
    return np.array(
        [
            [float(row["gt_x0"]), float(row["gt_y0"])],
            [float(row["gt_x1"]), float(row["gt_y1"])],
            [float(row["gt_x2"]), float(row["gt_y2"])],
            [float(row["gt_x3"]), float(row["gt_y3"])],
        ],
        dtype=np.float64,
    )


def gt_xywhr_from_polygon(polygon: np.ndarray):
    center = polygon.mean(axis=0)
    edge_w = polygon[1] - polygon[0]
    edge_h = polygon[2] - polygon[1]
    width = float(np.linalg.norm(edge_w))
    height = float(np.linalg.norm(edge_h))
    angle = float(math.atan2(edge_w[1], edge_w[0]))
    return np.array([center[0], center[1], width, height, angle], dtype=np.float32)


def gt_batch_from_row(row):
    if row["true_class"] == BACKGROUND_LABEL:
        return {
            "cls": torch.zeros((0,), dtype=torch.float32),
            "bboxes": torch.zeros((0, 5), dtype=torch.float32),
        }
    polygon = gt_polygon_from_row(row)
    class_id = float(row["true_class_id"])
    return {
        "cls": torch.as_tensor([class_id], dtype=torch.float32),
        "bboxes": torch.as_tensor(np.array([gt_xywhr_from_polygon(polygon)], dtype=np.float32), dtype=torch.float32),
    }


def read_rows(path: Path):
    with path.open("r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def resolve_image_path(value: str, base_dir: Path):
    path = Path(value)
    if path.is_absolute():
        return path
    return base_dir / path


def draw_debug(bgr, gt_polygon, det, sample, true_name, pred_name, correct):
    out = bgr.copy()
    if len(gt_polygon):
        gt = np.round(gt_polygon).astype(np.int32)
        cv2.polylines(out, [gt], True, (0, 255, 0), 2)
        cv2.putText(out, f"GT {true_name}", tuple(gt[0]), cv2.FONT_HERSHEY_SIMPLEX, 0.62, (0, 255, 0), 2)
    else:
        cv2.putText(out, "GT background", (16, 108), cv2.FONT_HERSHEY_SIMPLEX, 0.62, (0, 255, 0), 2)

    if det.valid:
        pred = np.array(det.corners_px, dtype=np.int32)
        cv2.polylines(out, [pred], True, (0, 255, 255), 2)
        cv2.circle(out, tuple(np.round(det.center_px).astype(int)), 4, (0, 0, 255), -1)

    status = "OK" if correct else "FAIL"
    color = (0, 180, 0) if correct else (0, 0, 255)
    height, width = out.shape[:2]
    cv2.rectangle(out, (8, 8), (width - 8, 78), (20, 20, 20), -1)
    cv2.putText(out, f"{sample} {status} true={true_name} pred={pred_name}", (16, 34), cv2.FONT_HERSHEY_SIMPLEX, 0.68, color, 2)
    cv2.putText(out, f"conf={det.confidence:.2f}", (16, 62), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (230, 230, 230), 2)
    return out


def write_samples_csv(out_dir, rows):
    path = out_dir / "samples_evaluated.csv"
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    return path


def write_confusion_csv(out_dir, matrix):
    path = out_dir / "confusion_matrix.csv"
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Predicted\\True"] + MATRIX_LABELS)
        for row_label, values in zip(MATRIX_LABELS, matrix):
            writer.writerow([row_label] + [int(v) for v in values])
    return path


def write_ultralytics_confusion_plots(out_dir, confusion: ConfusionMatrix):
    os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")
    confusion.plot(normalize=False, save_dir=out_dir)
    confusion.plot(normalize=True, save_dir=out_dir)
    return out_dir / "confusion_matrix.png", out_dir / "confusion_matrix_normalized.png"


def write_summary(out_dir, matrix, rows, args, eval_csv, matrix_csv, matrix_png):
    total = int(matrix[:, : len(TRUE_LABELS)].sum())
    correct = int(matrix[0, 0] + matrix[1, 1])
    accuracy = correct / max(1, total)
    background_rows = [row for row in rows if row["true_class"] == BACKGROUND_LABEL]
    background_total = len(background_rows)
    background_fp = sum(1 for row in background_rows if row.get("pred_class") not in ("", "no_detection"))
    background_fp_rate = background_fp / max(1, background_total)
    lines = [
        "# YOLO OBB Confusion Matrix Summary",
        "",
        f"- samples_csv: `{args.samples_csv}`",
        f"- evaluated_csv: `{eval_csv}`",
        f"- confusion_csv: `{matrix_csv}`",
        f"- confusion_png: `{matrix_png}`",
        f"- confusion_normalized_png: `{out_dir / 'confusion_matrix_normalized.png'}`",
        f"- model: `{args.model}`",
        f"- confidence_threshold: `{args.conf}`",
        f"- iou_threshold: `{args.iou_thres}`",
        f"- count: `{total}`",
        f"- correct: `{correct}`",
        f"- accuracy: `{accuracy * 100.0:.2f}%`",
        f"- background_count: `{background_total}`",
        f"- background_false_positive: `{background_fp}`",
        f"- background_false_positive_rate: `{background_fp_rate * 100.0:.2f}%`",
        "",
        "| true class | total | recall | correct | background_FN |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for row_idx, label in enumerate(TRUE_LABELS):
        row_total = int(matrix[:, row_idx].sum())
        recall = float(matrix[row_idx, row_idx] / max(1, row_total))
        lines.append(
            f"| `{label}` | {row_total} | {recall * 100.0:.2f}% | {int(matrix[row_idx, row_idx])} | "
            f"{int(matrix[len(TRUE_LABELS), row_idx])} |"
        )

    if rows:
        low_visible = sum(1 for row in rows if int(row.get("visible", 1)) == 0)
        glare = sum(1 for row in rows if int(row.get("glare", 0)) == 1)
        line_glare = sum(1 for row in rows if int(row.get("line_glare", 0)) == 1)
        lines.extend(
            [
                "",
                "## Sample Conditions",
                "",
                f"- low_visibility_samples: `{low_visible}`",
                f"- ellipse_glare_samples: `{glare}`",
                f"- line_glare_samples: `{line_glare}`",
            ]
        )

    path = out_dir / "summary.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main():
    args = parse_args()
    samples_csv = Path(args.samples_csv).expanduser().resolve()
    out_dir = Path(args.out_dir).expanduser().resolve() if args.out_dir else samples_csv.parent
    out_dir.mkdir(parents=True, exist_ok=True)
    debug_dir = out_dir / "images" / "eval"
    debug_dir.mkdir(parents=True, exist_ok=True)

    rows = read_rows(samples_csv)
    if not rows:
        raise RuntimeError(f"No rows found: {samples_csv}")

    model = YOLO(args.model)
    confusion = ConfusionMatrix(names=CLASS_NAMES, task="detect")
    evaluated_rows = []

    for idx, row in enumerate(rows):
        true_name = row["true_class"]
        if true_name not in TRUE_LABELS and true_name != BACKGROUND_LABEL:
            raise ValueError(f"Unknown true_class in row {idx}: {true_name}")
        image_path = resolve_image_path(row["raw_image"], samples_csv.parent)
        bgr = cv2.imread(str(image_path))
        if bgr is None:
            raise RuntimeError(f"Failed to read image: {image_path}")

        result = predict_result(model, bgr, args)
        detections = detections_from_result(result)
        confusion.process_batch(detections, gt_batch_from_row(row), conf=args.conf, iou_thres=args.iou_thres)

        det = best_obb_detection(result) if result is not None else empty_obb()
        pred_name = pred_name_from_det(det)
        correct = (pred_name == true_name) if true_name != BACKGROUND_LABEL else pred_name == "no_detection"

        debug_image = ""
        if args.save_images == "all" or (args.save_images == "failures" and not correct):
            polygon = gt_polygon_from_row(row)
            sample = row.get("sample", str(idx))
            debug = draw_debug(bgr, polygon, det, sample, true_name, pred_name, correct)
            debug_image = str(debug_dir / f"{int(sample):04d}_{true_name}_as_{pred_name}.png")
            cv2.imwrite(debug_image, debug)

        updated = dict(row)
        updated.update(
            {
                "pred_class": pred_name,
                "pred_class_id": det.class_id if det.valid else -1,
                "correct": int(correct),
                "confidence": f"{det.confidence:.6f}",
                "eval_debug_image": debug_image,
            }
        )
        evaluated_rows.append(updated)

        if (idx + 1) % 10 == 0 or idx + 1 == len(rows):
            matrix = confusion.matrix
            correct_count = sum(1 for item in evaluated_rows if int(item["correct"]) == 1)
            print(f"[eval] {idx + 1}/{len(rows)} samples, correct={correct_count}/{idx + 1}", flush=True)

    matrix = confusion.matrix
    eval_csv = write_samples_csv(out_dir, evaluated_rows)
    matrix_csv = write_confusion_csv(out_dir, matrix)
    matrix_png, matrix_normalized_png = write_ultralytics_confusion_plots(out_dir, confusion)
    summary = write_summary(out_dir, matrix, evaluated_rows, args, eval_csv, matrix_csv, matrix_png)

    print("\n=== YOLO OBB confusion matrix ===")
    print(f"samples:      {samples_csv}")
    print(f"evaluated:    {eval_csv}")
    print(f"matrix_csv:   {matrix_csv}")
    print(f"matrix_png:   {matrix_png}")
    print(f"matrix_norm:  {matrix_normalized_png}")
    print(f"summary:      {summary}")
    print(f"matrix:\n{matrix}")
    print("=================================\n")


if __name__ == "__main__":
    main()
